// Hand-written types mirroring the backend Pydantic schemas.
// This is the contract the whole frontend depends on — keep it exact.

export type Role = "admin" | "editor" | "viewer";
export type ReadingStatus = "to_read" | "reading" | "read";
export type Lang = "en" | "it" | "es" | "fr";
// Must match the backend DB enums (catalog enums.py) exactly.
export type BookCondition = "new" | "good" | "fair" | "poor";
export type BookSource = "purchased" | "gift" | "borrowed" | "other";

// ----- Auth -----

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type: "bearer";
}

export interface RegisterRequest {
  family_name: string;
  admin_email: string;
  admin_password: string;
  admin_full_name: string;
}

export interface RegisterResponse {
  family_id: string;
  user_id: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface ForgotPasswordRequest {
  email: string;
}

export interface ResetPasswordRequest {
  token: string;
  new_password: string;
}

// Claims encoded in the JWT access token.
export interface JwtClaims {
  sub: string; // user_id
  email: string;
  family_id: string;
  role: Role;
  exp: number; // seconds since epoch
}

// ----- Users & Family -----

export interface User {
  id: string;
  family_id: string;
  email: string;
  full_name: string;
  role: Role;
  is_active: boolean;
  annual_reading_goal: number | null;
  language: Lang | null;
  theme_name: "pergamena" | "akabeni" | "sumi" | null;
  theme_mode: "light" | "dark" | "system" | null;
}

export interface UserCreate {
  email: string;
  full_name: string;
  role: Role;
}

export interface UserUpdate {
  full_name?: string;
  role?: Role;
  is_active?: boolean;
  annual_reading_goal?: number | null;
}

export interface MeUpdate {
  full_name?: string;
  annual_reading_goal?: number | null;
  language?: Lang | null;
  theme_name?: "pergamena" | "akabeni" | "sumi" | null;
  theme_mode?: "light" | "dark" | "system" | null;
}

export interface Family {
  id: string;
  name: string;
  description: string | null;
}

export interface FamilyUpdate {
  name?: string;
  description?: string;
}

// POST v1/families/{id}/confirm-deletion and DELETE v1/families/{id} (auth-service) —
// both require this same proof of intent; the delete endpoint re-checks it
// itself even if confirm-deletion already ran.
export interface DeleteFamilyRequest {
  password: string;
  confirm_family_name: string;
}

// DELETE v1/catalog/account (catalog-service) — the library-data half of
// full account deletion, called before the auth-service family delete above.
export interface DeleteFamilyDataResponse {
  rooms_deleted: number;
  bookcases_deleted: number;
  records_deleted: number;
  owned_books_deleted: number;
  removed_members_deleted: number;
}

// ----- Catalog: records & books -----

// Normalized genre codes — mirrors the backend Genre enum (catalog-service).
export const GENRE_CODES = [
  "fiction",
  "fantasy",
  "science_fiction",
  "mystery_thriller",
  "romance",
  "horror",
  "historical",
  "biography_memoir",
  "history",
  "science",
  "philosophy",
  "religion",
  "self_help",
  "business",
  "art",
  "poetry",
  "drama",
  "comics",
  "children",
  "young_adult",
  "travel",
  "cooking",
  "essay",
  "reference",
  "other",
] as const;

export type Genre = (typeof GENRE_CODES)[number];

export interface GenreCount {
  genre: string;
  count: number;
}

// Book "presentation" (incipit). Resolved by catalog (free editorial description /
// stored / manual) or generated by the optional AI service.
export interface Incipit {
  text: string | null;
  source: string | null;
  generated_at: string | null;
}

export interface IncipitGenerateResult {
  text: string | null;
  model: string | null;
}

export interface BibliographicRecord {
  id: string;
  family_id: string;
  title: string;
  main_author: string | null;
  other_authors: string[];
  isbn: string | null;
  publisher: string | null;
  publication_year: number | null;
  language: string | null;
  genre: string | null;
  genre_raw: string | null;
  cover_url: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface BibliographicRecordCreate {
  title: string;
  main_author?: string | null;
  other_authors?: string[] | null;
  isbn?: string | null;
  publisher?: string | null;
  publication_year?: number | null;
  language?: string | null;
  genre?: string | null;
  cover_url?: string | null;
  notes?: string | null;
}

export type BibliographicRecordUpdate = Partial<BibliographicRecordCreate>;

export interface OwnedBook {
  id: string;
  family_id: string;
  bibliographic_record_id: string;
  room_id: string | null;
  bookcase_id: string | null;
  section_id: string | null;
  shelf_id: string | null;
  shelf_position: number | null;
  condition: string | null;
  purchase_date: string | null;
  purchase_price: string | null;
  source: string | null;
  reading_status: ReadingStatus;
  current_reader_id: string | null;
  owner_id: string | null;
  notes: string | null;
  tags: string[];
  is_intentional_duplicate: boolean;
  created_at: string;
  updated_at: string;
}

export interface OwnedBookCreate {
  bibliographic_record_id?: string;
  title?: string;
  main_author?: string;
  isbn?: string;
  room_id?: string;
  bookcase_id?: string;
  section_id?: string;
  shelf_id?: string;
  shelf_position?: number;
  condition?: BookCondition;
  purchase_date?: string;
  purchase_price?: number;
  source?: BookSource;
  reading_status?: ReadingStatus;
  owner_id?: string;
  notes?: string;
  tags?: string[];
  // Set to true to confirm adding despite a 409 DuplicateBookConflict from a previous call.
  is_intentional_duplicate?: boolean;
}

// 409 body from POST v1/books/ when the family already owns this book — the
// check is family-wide, not scoped to an owner (two members can legitimately
// each have their own copy), so the conflict surfaces who already has it and
// where, letting the user decide whether to add a separate copy anyway.
export interface DuplicateBookConflict {
  error: "duplicate_book";
  conflict_type: "isbn_match" | "title_author_match";
  existing_book_id: string;
  existing_record_id: string;
  title: string;
  main_author: string | null;
  isbn: string | null;
  existing_owner_id: string | null;
  existing_room_id: string | null;
  existing_bookcase_id: string | null;
  existing_section_id: string | null;
  existing_shelf_id: string | null;
}

export interface OwnedBookUpdate {
  room_id?: string | null;
  bookcase_id?: string | null;
  section_id?: string | null;
  shelf_id?: string | null;
  shelf_position?: number | null;
  condition?: BookCondition | null;
  purchase_date?: string | null;
  purchase_price?: number | null;
  source?: BookSource | null;
  reading_status?: ReadingStatus | null;
  owner_id?: string | null;
  tags?: string[] | null;
  notes?: string | null;
}

export interface BookRead {
  owned_book_id: string;
  user_id: string;
  read_at: string;
}

export interface BookLoan {
  id: string;
  owned_book_id: string;
  borrower_name: string;
  loaned_at: string;
  due_date: string | null;
  returned_at: string | null;
}

export interface BookLoanCreate {
  borrower_name: string;
  due_date?: string | null;
}

// The joined view the UI actually renders.
export interface BookView {
  book: OwnedBook;
  record: BibliographicRecord | null;
}

// ----- ISBN ingestion -----

export interface IsbnLookupResponse {
  source: string;
  metadata: Record<string, unknown>;
  cached: boolean;
}

export interface BookSearchResponse {
  results: Record<string, unknown>[];
}

// ----- AI: Cover OCR -----

export interface CoverExtractResponse {
  title: string;
  author: string;
  validated: boolean;
  confidence: number;
  raw_ocr_blocks: string[] | null;
}

// ----- Locations -----

export interface Room {
  id: string;
  family_id: string;
  name: string;
  description: string | null;
  created_at: string;
  updated_at: string;
}

export interface RoomCreate {
  name: string;
  description?: string | null;
}
export type RoomUpdate = Partial<RoomCreate>;

export interface Bookcase {
  id: string;
  room_id: string;
  family_id: string;
  name: string;
  description: string | null;
  type: string | null;
  notes: string | null;
  image_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface BookcaseCreate {
  room_id: string;
  name: string;
  description?: string | null;
  type?: string | null;
  notes?: string | null;
  image_url?: string | null;
}
export type BookcaseUpdate = Partial<BookcaseCreate>;

export interface Section {
  id: string;
  bookcase_id: string;
  section_index: number;
  label: string | null;
  created_at: string;
  updated_at: string;
}

export interface SectionCreate {
  bookcase_id: string;
  section_index: number;
  label?: string | null;
}
export type SectionUpdate = Partial<SectionCreate>;

export interface Shelf {
  id: string;
  section_id: string;
  shelf_index: number;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface ShelfCreate {
  section_id: string;
  shelf_index: number;
  notes?: string | null;
}
export type ShelfUpdate = Partial<ShelfCreate>;

// ----- Bookcase map -----

export interface BookOnShelf {
  id: string;
  title: string | null;
  main_author: string | null;
  reading_status: ReadingStatus;
}

export interface ShelfMap {
  shelf_id: string;
  shelf_index: number;
  books: BookOnShelf[];
}

export interface SectionMap {
  section_id: string;
  section_index: number;
  label: string | null;
  shelves: ShelfMap[];
}

export interface BookcaseMap {
  bookcase_id: string;
  bookcase_name: string;
  sections: SectionMap[];
}

// ----- Full library backup / restore -----
// Separate from BibliographicRecord/OwnedBook above (those mirror only the
// fields the everyday UI uses) so the backup is a complete, lossless 1:1
// mirror of every backend field, matching the catalog-service export schemas.

export interface BibliographicRecordExportItem {
  id: string;
  title: string;
  main_author: string | null;
  other_authors: string[];
  isbn: string | null;
  publisher: string | null;
  publication_year: number | null;
  language: string | null;
  genre: string | null;
  genre_raw: string | null;
  cover_url: string | null;
  notes: string | null;
  incipit: string | null;
  incipit_source: string | null;
  incipit_generated_at: string | null;
}

export interface OwnedBookExportItem {
  id: string;
  bibliographic_record_id: string;
  room_id: string | null;
  bookcase_id: string | null;
  section_id: string | null;
  shelf_id: string | null;
  shelf_position: number | null;
  position_description: string | null;
  condition: string | null;
  purchase_date: string | null;
  purchase_price: string | null;
  source: string | null;
  reading_status: ReadingStatus;
  current_reader_id: string | null;
  owner_id: string | null;
  tags: string[];
  notes: string | null;
  is_intentional_duplicate: boolean;
  duplicate_notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface BookHistory {
  id: string;
  owned_book_id: string;
  event_type: string;
  changed_by: string;
  old_data: Record<string, unknown> | null;
  new_data: Record<string, unknown> | null;
  created_at: string;
}

// A former family member's identity, captured the moment they're removed
// from the family (POST v1/catalog/members/removed) — auth-service hard-
// deletes the row, so this is the only place their name/email survive for
// a future export/import to recreate the real account from.
export interface RemovedMember {
  id: string;
  full_name: string;
  email: string;
  role: Role;
  removed_at: string;
}

export interface RemovedMemberCreate {
  id: string;
  full_name: string;
  email: string;
  role: Role;
}

// GET v1/users/export (auth-service)
export interface FamilyDataExport {
  schema_version: number;
  family: Family;
  users: User[];
}

// GET v1/catalog/export/full (catalog-service)
export interface FullLibraryExport {
  schema_version: number;
  exported_at: string;
  rooms: Room[];
  bookcases: Bookcase[];
  sections: Section[];
  shelves: Shelf[];
  bibliographic_records: BibliographicRecordExportItem[];
  owned_books: OwnedBookExportItem[];
  book_reads: BookRead[];
  book_loans: BookLoan[];
  book_history: BookHistory[];
  removed_members: RemovedMember[];
}

// The single downloaded file — FamilyDataExport + FullLibraryExport merged client-side.
export interface FullBackupExport {
  schema_version: number;
  exported_at: string;
  family: Family;
  users: User[];
  rooms: Room[];
  bookcases: Bookcase[];
  sections: Section[];
  shelves: Shelf[];
  bibliographic_records: BibliographicRecordExportItem[];
  owned_books: OwnedBookExportItem[];
  book_reads: BookRead[];
  book_loans: BookLoan[];
  book_history: BookHistory[];
  removed_members: RemovedMember[];
}

// POST v1/users/import (auth-service) — runs first, its user_id_map feeds the catalog import below.
// `users` may include entries recovered from removed-member snapshots (real
// email/full_name/role of a former member) alongside the current roster —
// both go through the same match-or-invite path on the backend.
export interface ImportUsersRequest {
  users: User[];
}

export interface ImportUsersResponse {
  user_id_map: Record<string, string>;
  created: number;
  matched: number;
}

// POST v1/catalog/import/full (catalog-service)
export interface ImportFullLibraryRequest {
  rooms: Room[];
  bookcases: Bookcase[];
  sections: Section[];
  shelves: Shelf[];
  bibliographic_records: BibliographicRecordExportItem[];
  owned_books: OwnedBookExportItem[];
  book_reads: BookRead[];
  book_loans: BookLoan[];
  book_history: BookHistory[];
  user_id_map: Record<string, string>;
}

export interface ImportFullLibraryResponse {
  rooms_imported: number;
  rooms_deduped: number;
  bookcases_imported: number;
  bookcases_deduped: number;
  sections_imported: number;
  sections_deduped: number;
  shelves_imported: number;
  shelves_deduped: number;
  records_imported: number;
  records_deduped: number;
  owned_books_imported: number;
  owned_books_deduped: number;
  book_reads_imported: number;
  book_loans_imported: number;
  book_history_imported: number;
}
