import {
  useMutation,
  useQuery,
  useQueryClient,
} from "@tanstack/react-query";

import { AI_REQUEST_TIMEOUT_MS, api } from "@/lib/api";
import { RECORDS } from "@/lib/paths";
import type {
  BibliographicRecord,
  BibliographicRecordCreate,
  BibliographicRecordUpdate,
  Incipit,
  TagSuggestionResult,
} from "@/types/api";

export const recordKeys = {
  all: ["records"] as const,
  list: (q: string, limit: number, offset: number) =>
    [...recordKeys.all, "list", { q, limit, offset }] as const,
  detail: (id: string) => [...recordKeys.all, "detail", id] as const,
  incipit: (id: string) => [...recordKeys.all, "incipit", id] as const,
};

export function useRecords(q = "", limit = 50, offset = 0) {
  return useQuery({
    queryKey: recordKeys.list(q, limit, offset),
    queryFn: () => {
      const searchParams: Record<string, string | number> = { limit, offset };
      if (q) searchParams.q = q;
      return api
        .get(`${RECORDS}/`, { searchParams })
        .json<BibliographicRecord[]>();
    },
  });
}

export function useRecord(id: string | undefined) {
  return useQuery({
    queryKey: recordKeys.detail(id ?? ""),
    queryFn: () => api.get(`${RECORDS}/${id}`).json<BibliographicRecord>(),
    enabled: Boolean(id),
  });
}

export function useCreateRecord() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (body: BibliographicRecordCreate) =>
      api.post(`${RECORDS}/`, { json: body }).json<BibliographicRecord>(),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: recordKeys.all });
    },
  });
}

export function useUpdateRecord() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }: { id: string; body: BibliographicRecordUpdate }) =>
      api.patch(`${RECORDS}/${id}`, { json: body }).json<BibliographicRecord>(),
    onSuccess: (record) => {
      qc.setQueryData(recordKeys.detail(record.id), record);
      void qc.invalidateQueries({ queryKey: recordKeys.all });
    },
  });
}

// Lazily resolves the book presentation: stored value, else free editorial description.
export function useIncipit(id: string | undefined) {
  return useQuery({
    queryKey: recordKeys.incipit(id ?? ""),
    queryFn: () => api.get(`${RECORDS}/${id}/incipit`).json<Incipit>(),
    enabled: Boolean(id),
    staleTime: Infinity,
  });
}

// Persist a presentation supplied manually or generated by the AI service.
export function useSetIncipit() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, text, source }: { id: string; text: string; source: "manual" | "ai" }) =>
      api.put(`${RECORDS}/${id}/incipit`, { json: { text, source } }).json<Incipit>(),
    onSuccess: (incipit, { id }) => {
      qc.setQueryData(recordKeys.incipit(id), incipit);
    },
  });
}

// Asks catalog to generate and persist an AI presentation for the given record.
// Catalog enriches context (Open Library description, publisher, year) before
// calling ai-service internally. Returns { text: null } when the LLM is disabled.
export function useGenerateIncipitAI() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      api
        .post(`${RECORDS}/${id}/incipit/generate`, { timeout: AI_REQUEST_TIMEOUT_MS })
        .json<Incipit>(),
    onSuccess: (incipit, id) => {
      qc.setQueryData(recordKeys.incipit(id), incipit);
    },
  });
}

export function useSuggestTags() {
  return useMutation({
    mutationFn: (id: string) =>
      api
        .post(`${RECORDS}/${id}/tags/suggest`, { timeout: AI_REQUEST_TIMEOUT_MS })
        .json<TagSuggestionResult>(),
  });
}

export function useDeleteRecord() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => api.delete(`${RECORDS}/${id}`).then(() => id),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: recordKeys.all });
    },
  });
}
